### ISSUE TITLE
Running example fails

### ISSUE THREAD

**Issue by inductor** [containers/libkrun#14]
Trying to run this with CentOS 8 and got the following error

Any idea what causing this?

```
$ LD_LIBRARY_PATH=/usr/local/lib64 RUST_BACKTRACE=full ./chroot_vm rootfs/ /bin/sh
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: CreateVsockBackend(UnixBind(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))', src/libkrun/src/lib.rs:156:55
stack backtrace:
   0:     0x7fcbd5ab1d8a - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x7fcbd5ab1d8a - std::backtrace_rs::backtrace::trace_unsynchronized::h1459b974b6fbe5e1
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fcbd5ab1d8a - std::sys_common::backtrace::_print_fmt::h9b8396a669123d95
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fcbd5ab1d8a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he009dcaaa75eed60
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fcbd5a4dc3c - core::fmt::write::h77b4746b0dea1dd3
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:     0x7fcbd5ab1571 - std::io::Write::write_fmt::heb7e50902e98831c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:     0x7fcbd5ab0f25 - std::sys_common::backtrace::_print::h2d880c9e69a21be9
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fcbd5ab0f25 - std::sys_common::backtrace::print::h5f02b1bb49f36879
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fcbd5ab0f25 - std::panicking::default_hook::{{closure}}::h658e288a7a809b29
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:     0x7fcbd5ab04e5 - std::panicking::default_hook::hb52d73f0da9a4bb8
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:     0x7fcbd5ab04e5 - std::panicking::rust_panic_with_hook::hfe7e1c684e3e6462
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:     0x7fcbd5acdb68 - std::panicking::begin_panic_handler::{{closure}}::h42939e004b32765c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499:13
  12:     0x7fcbd5acdadc - std::sys_common::backtrace::__rust_end_short_backtrace::h9d2070f7bf9fd56c
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7fcbd5acda8d - rust_begin_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:     0x7fcbd5a4c680 - core::panicking::panic_fmt::ha0bb065d9a260792
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:     0x7fcbd5a4e302 - core::option::expect_none_failed::h7e1dd0a94971eb61
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268:5
  16:     0x7fcbd5a9c3ea - krun_create_ctx
  17:           0x40088d - main
                               at /home/vagrant/libkrun/examples/chroot_vm.c:41:14
  18:     0x7fcbd569d7b3 - __libc_start_main
  19:           0x400a2e - _start
  20:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by slp** [comment]
That's probably because it can't create a listening UNIX socket at `/tmp/vsock0`. Perhaps this file already exists and it's owned by a different user?

BTW, this reminds me this is a leftover from the original vsock functionality and should be dropped. Will do ASAP.

**Comment by inductor** [comment]
@slp this is running on root user on a DigicealOcean Droplet.

**Comment by slp** [comment]
@inductor In 82940065ed04fd1bde7728e34f9e0b1a61fd3822, I dropped the legacy functionality that was creating this UNIX socket, so you shouldn't hit this problem anymore.

**Comment by slp** [comment]
@inductor Were you able to test this again? Are you still hitting this issue?

**Comment by inductor** [comment]
still not resolved with the latest upstream

```
RUST_BACKTRACE=full LD_LIBRARY_PATH=/usr/local/lib64 ./chroot_vm rootfs/ /bin/sh
thread '<unnamed>' panicked at 'Error creating the Kvm object: Error(2)', src/vmm/src/linux/vstate.rs:340:30
stack backtrace:
   0:     0x7fdc1822fa8e - std::backtrace_rs::backtrace::libunwind::trace::h25e12e0d899beba0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7fdc1822fa8e - std::backtrace_rs::backtrace::trace_unsynchronized::h70e61195d6ae3df6
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdc1822fa8e - std::sys_common::backtrace::_print_fmt::hba93ab80d779695a
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fdc1822fa8e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf092b5883b4b2e50
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fdc181cf32c - core::fmt::write::hf68bc350a8f2f0dc
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:     0x7fdc1822f191 - std::io::Write::write_fmt::hf66811b1bc767436
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:     0x7fdc1822eb35 - std::sys_common::backtrace::_print::hd425a11bfe1f20f8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fdc1822eb35 - std::sys_common::backtrace::print::h6d678795c1e61e13
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fdc1822eb35 - std::panicking::default_hook::{{closure}}::h78a02a4a0dee5e7e
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:     0x7fdc1822e1d6 - std::panicking::default_hook::h56eb7eda02f355a7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:     0x7fdc1822e1d6 - std::panicking::rust_panic_with_hook::hb27ea14285131c61
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:     0x7fdc1824d438 - std::panicking::begin_panic_handler::{{closure}}::hc552fcee62aad17f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:     0x7fdc1824d3ac - std::sys_common::backtrace::__rust_end_short_backtrace::hb9f0aa9a78e885a0
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x7fdc1824d35d - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:     0x7fdc181cdda0 - core::panicking::panic_fmt::h12ac4570ea43d06f
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:     0x7fdc181cf9d2 - core::option::expect_none_failed::h096fa60f757b7204
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
  16:     0x7fdc18277797 - vmm::builder::build_microvm::ha0b1f005eaf04789
  17:     0x7fdc181cba0b - krun_start_enter
  18:           0x400c28 - main
                               at /root/libkrun/examples/chroot_vm.c:138:15
  19:     0x7fdc17e167b3 - __libc_start_main
  20:           0x400dee - _start
  21:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by orimanabu** [comment]
The error message looks like `Kvm::new()` failed, do you have `/dev/kvm` on your node?

**Comment by slp** [comment]
Closing due to inactivity.
